In [20]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import random

In [2]:
res = ['Cat/0.jpg', 'Cat/1.jpg', 'Cat/2.jpg', 'Cat/3.jpg', 'Cat/4.jpg', 'Cat/5.jpg', 'Cat/6.jpg', 'Cat/7.jpg', 'Cat/8.jpg', 'Cat/9.jpg', 'Cat/10.jpg', 
      'Cat/11.jpg', 'Cat/12.jpg', 'Cat/13.jpg', 'Cat/14.jpg', 'Cat/15.jpg', 'Cat/16.jpg', 'Cat/17.jpg', 'Cat/18.jpg', 'Cat/19.jpg', 'Cat/20.jpg', 'Cat/21.jpg']

In [3]:
fig = plt.figure(figsize=(8, 8))
columns = 4
rows = 5
for i in range(1, columns*rows+1):
    img = Image.open('/Users/dimasyrovitsky/Documents/nn_without_frameworks/PetImages/Cat/'+res[i])
    fig.add_subplot(rows, columns, i)
    plt.imshow(img)
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/dimasyrovitsky/Documents/nn_without_frameworks/PetImages/Cat/Cat/1.jpg'

<Figure size 576x576 with 0 Axes>

In [4]:
X = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
X.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [6]:
X.mean(axis=1)

array([2., 5., 8.])

In [7]:
s = np.square((X - X.mean(axis=1)) ** 2) / 2
s

array([[  0.5,  40.5, 312.5],
       [  8. ,   0. ,   8. ],
       [312.5,  40.5,   0.5]])

In [8]:
X - X.mean(axis=1) / s

/var/folders/c6/_zhl81td4_7dslytk2yh2p6c0000gn/T/ipykernel_22284/654110722.py:1: RuntimeWarning: divide by zero encountered in true_divide
  X - X.mean(axis=1) / s


array([[-3.        ,  1.87654321,  2.9744    ],
       [ 3.75      ,        -inf,  5.        ],
       [ 6.9936    ,  7.87654321, -7.        ]])

In [9]:
(X - X.mean()) / X.std()

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [10]:
(X - X.min()) / (X.max() - X.min())

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [11]:
y = np.array([1, 1, 1, 1, 1])
p = np.array([1, 0, 1, 0, 1])

In [12]:
for i in range(len(y)):
    if y[i] != p[i]:
        print(i)

1
3


In [13]:
np.squeeze(y)

array([1, 1, 1, 1, 1])

In [17]:
np.array(y.shape[1], 3)

IndexError: tuple index out of range

In [31]:
random.sample(range(100), 3)

[84, 35, 95]

In [33]:
a = np.zeros((5, 6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [46]:
b = np.array((1, 2, 3, 4, 5))
b

array([1, 2, 3, 4, 5])

In [47]:
a[:,0] = b
a

array([[1., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0.]])

In [54]:
c = np.ones((5, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
a[:, 1] = c[:, 1]
a

array([[1., 1., 0., 0., 0., 0.],
       [2., 1., 0., 0., 0., 0.],
       [3., 1., 0., 0., 0., 0.],
       [4., 1., 0., 0., 0., 0.],
       [5., 1., 0., 0., 0., 0.]])